---
- name: Install and configure OpenIO account
  any_errors_fatal: true
  hosts: account
  become : true
  gather_facts: false
  environment: "{{ openio_environment }}"
  pre_tasks:
    - name: refresh facts
      setup:
      when: ansible_default_ipv4 is not defined

  roles:
    - role: account
      openio_account_namespace: "{{ namespace }}"
      openio_account_gridinit_dir: "/etc/gridinit.d/"
      openio_account_gridinit_file_prefix: "{{ namespace }}-"
...
